### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by topa** [topa/gignx#7]
- [ ] [Project Structure](/topa/gignx/issues/9): Bower, Grunt, folder, files (configs, main.js)
- [ ] [Testing](/topa/gignx/issues/12): test-runner, test-driver, CI/Travis, running
- [ ] [Debugging](/topa/gignx/issues/10): breakpoints, logging, object inspection
- [x] [Code-Style-Guide/Cheat-Sheet](/topa/gignx/issues/11): gnome extension guidelines
- [x] [Organization](/topa/gignx/issues/8): Burndown-Chart (server or gist?), code reviews, milestones
